// Mock data for development and testing
import { User, Agency, Client, Project, Task, Meeting, Contact, Role, UserActivity } from './index';

// Role definitions
export const ROLES: Role[] = [
  {
    id: 'role_1',
    name: 'super_admin',
    displayName: 'Super Admin',
    permissions: [
      { id: 'p1', name: 'view_all_data', description: 'View all system data' },
      { id: 'p2', name: 'manage_users', description: 'Manage users and roles' },
      { id: 'p3', name: 'manage_agencies', description: 'Manage agencies' },
      { id: 'p4', name: 'view_technical_vault', description: 'Access technical vault' },
      { id: 'p5', name: 'approve_projects', description: 'Approve projects' },
    ],
    description: 'Full system control',
  },
  {
    id: 'role_2',
    name: 'admin',
    displayName: 'Admin / Assistant',
    permissions: [
      { id: 'p1', name: 'view_all_data', description: 'View all system data' },
      { id: 'p4', name: 'view_technical_vault', description: 'Access technical vault' },
      { id: 'p6', name: 'manage_tasks', description: 'Create and assign tasks' },
    ],
    description: 'Operational support',
  },
  {
    id: 'role_3',
    name: 'manager',
    displayName: 'Manager / AM',
    permissions: [
      { id: 'p6', name: 'manage_tasks', description: 'Create and assign tasks' },
      { id: 'p7', name: 'approve_tasks', description: 'Approve task submissions' },
      { id: 'p8', name: 'view_team_projects', description: 'View team projects' },
      { id: 'p9', name: 'view_workload', description: 'View team workload' },
    ],
    description: 'Task planning and approvals',
  },
  {
    id: 'role_4',
    name: 'developer',
    displayName: 'Developer / Freelancer',
    permissions: [
      { id: 'p10', name: 'view_assigned_tasks', description: 'View assigned tasks' },
      { id: 'p11', name: 'submit_for_review', description: 'Submit task for review' },
      { id: 'p12', name: 'view_limited_project', description: 'View limited project context' },
    ],
    description: 'Execute assigned tasks',
  },
  {
    id: 'role_5',
    name: 'agency_user',
    displayName: 'Agency User',
    permissions: [
      { id: 'p13', name: 'submit_projects', description: 'Submit projects' },
      { id: 'p14', name: 'view_own_projects', description: 'View own projects' },
      { id: 'p15', name: 'upload_documents', description: 'Upload documents' },
    ],
    description: 'Submit and track projects',
  },
];

// Mock Users
export const MOCK_USERS: User[] = [
  {
    id: 'user_1',
    name: 'Sarah Chen',
    email: 'sarah@unfoldcro.com',
    phone: '+1-555-0101',
    role: 'super_admin',
    timezone: 'EST',
    avatar: '👩‍💼',
    status: 'active',
    created_at: '2025-01-01',
    updated_at: '2025-01-01',
  },
  {
    id: 'user_2',
    name: 'James Rodriguez',
    email: 'james@unfoldcro.com',
    phone: '+1-555-0102',
    role: 'admin',
    timezone: 'EST',
    avatar: '👨‍💼',
    status: 'active',
    created_at: '2025-01-01',
    updated_at: '2025-01-01',
  },
  {
    id: 'user_3',
    name: 'Emily Watson',
    email: 'emily@unfoldcro.com',
    phone: '+1-555-0103',
    role: 'manager',
    timezone: 'EST',
    avatar: '👩‍🔬',
    status: 'active',
    created_at: '2025-01-01',
    updated_at: '2025-01-01',
  },
  {
    id: 'user_4',
    name: 'Alex Kumar',
    email: 'alex@unfoldcro.com',
    phone: '+1-555-0104',
    role: 'developer',
    timezone: 'PST',
    avatar: '👨‍💻',
    status: 'active',
    created_at: '2025-01-01',
    updated_at: '2025-01-01',
  },
  {
    id: 'user_5',
    name: 'Mike Johnson',
    email: 'mike@unfoldcro.com',
    phone: '+1-555-0105',
    role: 'developer',
    timezone: 'CST',
    avatar: '👨‍🔧',
    status: 'active',
    created_at: '2025-01-01',
    updated_at: '2025-01-01',
  },
  {
    id: 'user_6',
    name: 'Agency Contact',
    email: 'contact@creativestudio.com',
    phone: '+1-555-0201',
    role: 'agency_user',
    agency_id: 'agency_1',
    timezone: 'EST',
    avatar: '🎨',
    status: 'active',
    created_at: '2025-01-01',
    updated_at: '2025-01-01',
  },
];

// Mock Agencies
export const MOCK_AGENCIES: Agency[] = [
  {
    id: 'agency_1',
    name: 'Creative Studio Pro',
    email: 'info@creativestudio.com',
    phone: '+1-555-1001',
    address: '123 Design St, New York, NY 10001',
    website: 'www.creativestudio.com',
    contact_person: 'Sarah Anderson',
    status: 'active',
    created_at: '2025-01-01',
    updated_at: '2025-01-01',
  },
  {
    id: 'agency_2',
    name: 'Digital Solutions Inc',
    email: 'sales@digitalsolutions.com',
    phone: '+1-555-1002',
    address: '456 Tech Ave, San Francisco, CA 94102',
    website: 'www.digitalsolutions.com',
    contact_person: 'John Miller',
    status: 'active',
    created_at: '2025-01-01',
    updated_at: '2025-01-01',
  },
];

// Mock Clients
export const MOCK_CLIENTS: Client[] = [
  {
    id: 'client_1',
    name: 'TechFlow Corp',
    agency_id: 'agency_1',
    email: 'contact@techflow.com',
    company: 'TechFlow Corporation',
    contact_person: 'Lisa Brown',
    tags: ['startup', 'saas'],
    created_by: 'user_6',
    created_at: '2025-01-15',
    updated_at: '2025-01-15',
  },
  {
    id: 'client_2',
    name: 'Fashion Forward LLC',
    agency_id: 'agency_1',
    email: 'info@fashionforward.com',
    company: 'Fashion Forward LLC',
    contact_person: 'Emma Wilson',
    tags: ['ecommerce', 'fashion'],
    created_by: 'user_6',
    created_at: '2025-01-20',
    updated_at: '2025-01-20',
  },
  {
    id: 'client_3',
    name: 'Global Logistics Pro',
    agency_id: 'agency_2',
    email: 'contact@globallogistics.com',
    company: 'Global Logistics Pro',
    contact_person: 'Robert Chang',
    tags: ['enterprise', 'logistics'],
    created_by: 'user_6',
    created_at: '2025-02-01',
    updated_at: '2025-02-01',
  },
];

// Mock Projects
export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj_1',
    name: 'TechFlow SaaS Dashboard Redesign',
    agency_id: 'agency_1',
    client_id: 'client_1',
    status: 'in_progress',
    type: 'website_development',
    website_category: 'saas',
    priority: 'high',
    pricing_model: 'fixed',
    deadline: '2026-03-15',
    created_by: 'user_6',
    assigned_manager: 'user_3',
    requirement_notes: 'Update dashboard UI with modern design standards',
    created_at: '2026-01-15',
    updated_at: '2026-02-10',
  },
  {
    id: 'proj_2',
    name: 'Fashion Forward E-Commerce Platform',
    agency_id: 'agency_1',
    client_id: 'client_2',
    status: 'pending_intake',
    type: 'ecommerce',
    website_category: 'ecommerce',
    priority: 'high',
    pricing_model: 'fixed',
    deadline: '2026-04-30',
    created_by: 'user_6',
    assigned_manager: 'user_3',
    requirement_notes: 'Full e-commerce platform with payment integration',
    created_at: '2026-02-05',
    updated_at: '2026-02-18',
  },
  {
    id: 'proj_3',
    name: 'Global Logistics Web Portal',
    agency_id: 'agency_2',
    client_id: 'client_3',
    status: 'in_progress',
    type: 'website_development',
    website_category: 'corporate',
    priority: 'urgent',
    pricing_model: 'hourly',
    deadline: '2026-03-01',
    created_by: 'user_6',
    assigned_manager: 'user_3',
    requirement_notes: 'Client tracking dashboard with real-time updates',
    created_at: '2026-01-20',
    updated_at: '2026-02-15',
  },
];

// Mock Tasks
export const MOCK_TASKS: Task[] = [
  {
    id: 'task_1',
    title: 'Design Dashboard Mockups',
    description: 'Create high-fidelity mockups for the new dashboard layout',
    project_id: 'proj_1',
    assigned_to: 'user_4',
    assigned_by: 'user_3',
    status: 'in_progress',
    priority: 'high',
    deadline: '2026-02-28',
    estimated_hours: 12,
    review_required: true,
    created_at: '2026-02-01',
    updated_at: '2026-02-15',
    type: 'feature',
    acceptance_criteria: [
      'Dashboard mockups completed in Figma',
      'Desktop and mobile layouts designed',
      'Color scheme and typography finalized',
      'Component library created'
    ]
  },
  {
    id: 'task_2',
    title: 'Frontend Development - Dashboard Components',
    description: 'Implement dashboard components using React and TypeScript',
    project_id: 'proj_1',
    assigned_to: 'user_5',
    assigned_by: 'user_3',
    status: 'sent_for_review',
    priority: 'high',
    deadline: '2026-03-05',
    estimated_hours: 20,
    actual_hours: 18,
    review_required: true,
    marked_for_review_at: '2026-02-15',
    created_at: '2026-02-05',
    updated_at: '2026-02-15',
    type: 'feature',
    acceptance_criteria: [
      'React components match Figma design',
      'All props properly typed in TypeScript',
      'Components are responsive',
      'Unit tests written with >80% coverage',
      'Storybook stories created'
    ]
  },
  {
    id: 'task_3',
    title: 'Database Schema Design',
    description: 'Design database schema for e-commerce platform',
    project_id: 'proj_2',
    assigned_to: 'user_4',
    assigned_by: 'user_3',
    status: 'not_started',
    priority: 'high',
    deadline: '2026-02-25',
    estimated_hours: 8,
    review_required: true,
    created_at: '2026-02-10',
    updated_at: '2026-02-15',
    type: 'feature',
    acceptance_criteria: [
      'Schema supports all product types',
      'Indexes optimized for query performance',
      'Scalable to 1M+ products',
      'Documentation includes ER diagram'
    ]
  },
  {
    id: 'task_4',
    title: 'API Integration - Payment Gateway',
    description: 'Integrate Stripe payment gateway with the e-commerce platform',
    project_id: 'proj_2',
    assigned_to: 'user_5',
    assigned_by: 'user_3',
    status: 'blocked',
    priority: 'urgent',
    deadline: '2026-03-10',
    estimated_hours: 16,
    review_required: true,
    created_at: '2026-02-08',
    updated_at: '2026-02-15',
    type: 'feature',
    acceptance_criteria: [
      'Stripe API integrated successfully',
      'Payment processing tested with test cards',
      'Error handling and retry logic implemented',
      'Transaction logs stored in database',
      'PCI DSS compliance verified'
    ]
  },
  {
    id: 'task_5',
    title: 'Setup Hosting Environment',
    description: 'Configure production hosting environment',
    project_id: 'proj_3',
    assigned_to: 'user_4',
    assigned_by: 'user_3',
    status: 'completed',
    priority: 'high',
    deadline: '2026-02-20',
    estimated_hours: 6,
    actual_hours: 5,
    review_required: false,
    completed_at: '2026-02-18',
    created_at: '2026-02-10',
    updated_at: '2026-02-18',
    type: 'refactor',
    acceptance_criteria: [
      'Server configured with auto-scaling',
      'SSL certificates installed',
      'Database backups automated',
      'Monitoring and alerting configured'
    ]
  },
];

// Mock Meetings
export const MOCK_MEETINGS: Meeting[] = [
  {
    id: 'meeting_1',
    title: 'Weekly Project Sync - TechFlow',
    description: 'Weekly sync to discuss progress and blockers',
    project_id: 'proj_1',
    scheduled_at: '2026-02-19T10:00:00',
    duration_minutes: 60,
    meeting_link: 'https://zoom.us/j/123456789',
    attendees: ['user_3', 'user_4', 'user_5'],
    created_by: 'user_3',
    created_at: '2026-02-15',
    updated_at: '2026-02-15',
  },
  {
    id: 'meeting_2',
    title: 'Client Meeting - Fashion Forward',
    description: 'Discuss project requirements and timeline',
    project_id: 'proj_2',
    scheduled_at: '2026-02-20T14:00:00',
    duration_minutes: 45,
    meeting_link: 'https://teams.microsoft.com/l/meetup-join/...',
    attendees: ['user_3', 'user_6'],
    created_by: 'user_3',
    created_at: '2026-02-15',
    updated_at: '2026-02-15',
  },
  {
    id: 'meeting_3',
    title: 'Urgent - Global Logistics Production Issues',
    description: 'Address critical production issues',
    project_id: 'proj_3',
    scheduled_at: '2026-02-18T16:00:00',
    duration_minutes: 90,
    attendees: ['user_3', 'user_4', 'user_5'],
    created_by: 'user_3',
    created_at: '2026-02-15',
    updated_at: '2026-02-15',
  },
];

// Mock Contacts
export const MOCK_CONTACTS: Contact[] = [
  {
    id: 'contact_1',
    name: 'Sarah Chen',
    email: 'sarah@unfoldcro.com',
    phone: '+1-555-0101',
    type: 'internal_team',
    tags: ['super_admin', 'management'],
    created_by: 'user_1',
    created_at: '2025-01-01',
    updated_at: '2025-01-01',
  },
  {
    id: 'contact_2',
    name: 'Lisa Brown - TechFlow',
    email: 'lisa@techflow.com',
    phone: '+1-555-2001',
    company: 'TechFlow Corp',
    type: 'client',
    tags: ['primary_contact', 'decision_maker'],
    linked_projects: ['proj_1'],
    created_by: 'user_6',
    created_at: '2026-01-15',
    updated_at: '2026-01-15',
  },
  {
    id: 'contact_3',
    name: 'Emma Wilson - Fashion Forward',
    email: 'emma@fashionforward.com',
    phone: '+1-555-2002',
    company: 'Fashion Forward LLC',
    type: 'client',
    tags: ['primary_contact'],
    linked_projects: ['proj_2'],
    created_by: 'user_6',
    created_at: '2026-01-20',
    updated_at: '2026-01-20',
  },
  {
    id: 'contact_4',
    name: 'Creative Studio Pro - Agency',
    email: 'info@creativestudio.com',
    phone: '+1-555-1001',
    company: 'Creative Studio Pro',
    type: 'agency',
    tags: ['active_partner'],
    linked_projects: ['proj_1', 'proj_2'],
    created_by: 'user_1',
    created_at: '2025-01-01',
    updated_at: '2025-01-01',
  },
];

// Mock User Activity Logs
export const MOCK_ACTIVITY_LOGS: UserActivity[] = [
  {
    id: 'activity_1',
    user_id: 'user_1',
    user_name: 'Sarah Chen',
    action: 'login',
    description: 'Logged in successfully',
    resource_type: 'auth',
    timestamp: '2026-02-18 14:30:00',
    ip_address: '192.168.1.100',
  },
  {
    id: 'activity_2',
    user_id: 'user_2',
    user_name: 'James Rodriguez',
    action: 'created',
    description: 'Created new project: E-commerce Platform',
    resource_type: 'project',
    resource_id: 'proj_3',
    timestamp: '2026-02-18 13:15:00',
    ip_address: '192.168.1.101',
  },
  {
    id: 'activity_3',
    user_id: 'user_3',
    user_name: 'Emily Watson',
    action: 'updated',
    description: 'Updated task status: Approved task "Database Schema"',
    resource_type: 'task',
    resource_id: 'task_5',
    timestamp: '2026-02-18 12:45:00',
    ip_address: '192.168.1.102',
  },
  {
    id: 'activity_4',
    user_id: 'user_4',
    user_name: 'Alex Kumar',
    action: 'logout',
    description: 'Logged out',
    resource_type: 'auth',
    timestamp: '2026-02-18 11:30:00',
    ip_address: '192.168.1.103',
  },
  {
    id: 'activity_5',
    user_id: 'user_1',
    user_name: 'Sarah Chen',
    action: 'deleted',
    description: 'Deleted user: Inactive Developer',
    resource_type: 'user',
    resource_id: 'user_7',
    timestamp: '2026-02-18 10:20:00',
    ip_address: '192.168.1.100',
  },
  {
    id: 'activity_6',
    user_id: 'user_2',
    user_name: 'James Rodriguez',
    action: 'updated',
    description: 'Changed user role: Alex Kumar (developer → manager)',
    resource_type: 'user',
    resource_id: 'user_4',
    timestamp: '2026-02-18 09:15:00',
    ip_address: '192.168.1.101',
  },
  {
    id: 'activity_7',
    user_id: 'user_5',
    user_name: 'Mike Johnson',
    action: 'created',
    description: 'Submitted project for review',
    resource_type: 'project',
    resource_id: 'proj_2',
    timestamp: '2026-02-18 08:45:00',
    ip_address: '192.168.1.104',
  },
  {
    id: 'activity_8',
    user_id: 'user_1',
    user_name: 'Sarah Chen',
    action: 'login',
    description: 'Logged in successfully',
    resource_type: 'auth',
    timestamp: '2026-02-17 15:00:00',
    ip_address: '192.168.1.100',
  },
];
